/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import pbl.autorama.Cliente;
import javax.swing.JOptionPane;
import org.eclipse.paho.client.mqttv3.MqttException;

/**
 *
 * @author mathe
 */
public class TelaFinal extends javax.swing.JFrame {
    
    DefaultListModel modelPilotos = new DefaultListModel();
    DefaultListModel modelCarros = new DefaultListModel();
    DefaultListModel modelEquipes = new DefaultListModel();
    DefaultListModel modelPistas = new DefaultListModel();
    DefaultListModel modelCorridas = new DefaultListModel();
    DefaultListModel modelTags = new DefaultListModel();
    
    /**
     * Creates new form TelaFinal
     */
    public TelaFinal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaPistas = new javax.swing.JList();
        BotaoAtualizarListaPistas = new javax.swing.JButton();
        LabelCarros = new javax.swing.JLabel();
        LabelCarros3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaPilotos = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        listaEquipes = new javax.swing.JList();
        BotaoAtualizarListaCarro = new javax.swing.JButton();
        BotaoAtualizarListaPilotos = new javax.swing.JButton();
        LabelCarros1 = new javax.swing.JLabel();
        LabelCarros2 = new javax.swing.JLabel();
        BotaoAtualizarListaEquipes = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaCarros = new javax.swing.JList();
        salvarDados = new javax.swing.JButton();
        preencherDados = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        modeloCarro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        marcaCarro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        corCarro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        numeroCarro = new javax.swing.JTextField();
        botaoCadastrarCarro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lerTags = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTags = new javax.swing.JList<>();
        botaoAtualizarTags = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaEquipesCadastroCarro = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomeEquipe = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        apelidoEquipe = new javax.swing.JTextField();
        nacionalidadeEquipe = new javax.swing.JTextField();
        anoEquipe = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pontosEquipe = new javax.swing.JTextField();
        botaoCadastrarEquipe = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nomePiloto = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        apelidoPiloto = new javax.swing.JTextField();
        nascimentoPiloto = new javax.swing.JTextField();
        nacionalidadePiloto = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        emAtividade = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pontosPiloto = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        botaoCadastrarPiloto = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        listaEquipesPiloto = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        listaCarrosPiloto = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        nomePista = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        paisPista = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        recordePista = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        donoRecordePista = new javax.swing.JTextField();
        botaoCadastrarPista = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        qualificacao = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        qtdVoltas = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        botaoComecarQualificacao = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        pistaCorrida = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane5.setViewportView(listaPistas);

        BotaoAtualizarListaPistas.setText("Atualizar lista");
        BotaoAtualizarListaPistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAtualizarListaPistasActionPerformed(evt);
            }
        });

        LabelCarros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCarros.setText("Lista de carros cadastrados");

        LabelCarros3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCarros3.setText("Lista de equipes cadastradas");

        jScrollPane4.setViewportView(listaPilotos);

        jScrollPane6.setViewportView(listaEquipes);

        BotaoAtualizarListaCarro.setText("Atualizar lista");
        BotaoAtualizarListaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAtualizarListaCarroActionPerformed(evt);
            }
        });

        BotaoAtualizarListaPilotos.setText("Atualizar lista");
        BotaoAtualizarListaPilotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAtualizarListaPilotosActionPerformed(evt);
            }
        });

        LabelCarros1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCarros1.setText("Lista de pilotos cadastrados");

        LabelCarros2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCarros2.setText("Lista de pistas cadastradas");

        BotaoAtualizarListaEquipes.setText("Atualizar lista");
        BotaoAtualizarListaEquipes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAtualizarListaEquipesActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(listaCarros);

        salvarDados.setText("Salvar Dados");
        salvarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarDadosActionPerformed(evt);
            }
        });

        preencherDados.setText("Preencher Dados");
        preencherDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preencherDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotaoAtualizarListaCarro)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LabelCarros)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BotaoAtualizarListaPilotos)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(LabelCarros1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 224, Short.MAX_VALUE)
                        .addComponent(preencherDados)
                        .addGap(86, 86, 86)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salvarDados)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BotaoAtualizarListaPistas, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCarros3)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelCarros2)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(BotaoAtualizarListaEquipes, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCarros)
                    .addComponent(LabelCarros3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoAtualizarListaEquipes)
                    .addComponent(BotaoAtualizarListaCarro))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LabelCarros2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoAtualizarListaPistas))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(LabelCarros1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoAtualizarListaPilotos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarDados)
                    .addComponent(preencherDados))
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Visão Geral", jPanel2);

        jLabel1.setText("Tag:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Cadastro de Carro");

        jLabel2.setText("Modelo:");

        modeloCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloCarroActionPerformed(evt);
            }
        });

        jLabel3.setText("Marca:");

        marcaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaCarroActionPerformed(evt);
            }
        });

        jLabel4.setText("Cor:");

        corCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corCarroActionPerformed(evt);
            }
        });

        jLabel5.setText("Número:");

        numeroCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroCarroActionPerformed(evt);
            }
        });

        botaoCadastrarCarro.setText("Cadastrar");
        botaoCadastrarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarCarroActionPerformed(evt);
            }
        });

        jLabel9.setText("Equipe:");

        lerTags.setText("Ler Tags");
        lerTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lerTagsActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listaTags);

        botaoAtualizarTags.setText("Atualizar lista");
        botaoAtualizarTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarTagsActionPerformed(evt);
            }
        });

        listaEquipesCadastroCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listaEquipesCadastroCarroMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(listaEquipesCadastroCarro);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoCadastrarCarro)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(marcaCarro)
                            .addComponent(modeloCarro)
                            .addComponent(corCarro)
                            .addComponent(numeroCarro)
                            .addComponent(jScrollPane2))))
                .addGap(103, 103, 103)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lerTags)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoAtualizarTags))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(294, 294, 294))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel8)
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(modeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(marcaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(corCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(numeroCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lerTags)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(botaoAtualizarTags))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(botaoCadastrarCarro)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Carros", jPanel3);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Cadastro de Equipe");

        jLabel7.setText("Nome:");

        nomeEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEquipeActionPerformed(evt);
            }
        });

        jLabel11.setText("Apelido:");

        apelidoEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apelidoEquipeActionPerformed(evt);
            }
        });

        nacionalidadeEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadeEquipeActionPerformed(evt);
            }
        });

        anoEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoEquipeActionPerformed(evt);
            }
        });

        jLabel12.setText("Nacionalidade:");

        jLabel13.setText("Ano:");

        jLabel16.setText("Pontos:");

        pontosEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontosEquipeActionPerformed(evt);
            }
        });

        botaoCadastrarEquipe.setText("Cadastrar");
        botaoCadastrarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarEquipeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel10)
                        .addGap(316, 316, 316))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botaoCadastrarEquipe))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pontosEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nacionalidadeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nomeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(apelidoEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(anoEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(220, 220, 220))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nomeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(apelidoEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(nacionalidadeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(anoEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(pontosEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoCadastrarEquipe)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Equipes", jPanel4);

        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Cadastro de Piloto");

        jLabel18.setText("Nome");

        nomePiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePilotoActionPerformed(evt);
            }
        });

        jLabel19.setText("Apelido");

        apelidoPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apelidoPilotoActionPerformed(evt);
            }
        });

        nascimentoPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nascimentoPilotoActionPerformed(evt);
            }
        });

        nacionalidadePiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadePilotoActionPerformed(evt);
            }
        });

        jLabel20.setText("Nacionalidade");

        jLabel21.setText("Data de nascimento:");

        jLabel22.setText("Em atividade");

        jLabel23.setText("Equipe");

        jLabel24.setText("Carro");

        pontosPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontosPilotoActionPerformed(evt);
            }
        });

        jLabel25.setText("Pontos");

        botaoCadastrarPiloto.setText("Cadastrar");
        botaoCadastrarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarPilotoActionPerformed(evt);
            }
        });

        listaEquipesPiloto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listaEquipesPilotoMouseEntered(evt);
            }
        });
        jScrollPane7.setViewportView(listaEquipesPiloto);

        listaCarrosPiloto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listaCarrosPilotoMouseEntered(evt);
            }
        });
        jScrollPane8.setViewportView(listaCarrosPiloto);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel24))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(botaoCadastrarPiloto))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pontosPiloto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emAtividade, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nacionalidadePiloto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nascimentoPiloto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apelidoPiloto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomePiloto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane7)
                                    .addComponent(jScrollPane8)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel17)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(nomePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(apelidoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(nascimentoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(nacionalidadePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pontosPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addComponent(botaoCadastrarPiloto)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pilotos", jPanel5);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Cadastro de Pista");

        jLabel27.setText("Nome:");

        nomePista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePistaActionPerformed(evt);
            }
        });

        jLabel28.setText("País:");

        paisPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisPistaActionPerformed(evt);
            }
        });

        jLabel29.setText("Recorde:");

        recordePista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordePistaActionPerformed(evt);
            }
        });

        jLabel30.setText("Dono do recorde:");

        donoRecordePista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donoRecordePistaActionPerformed(evt);
            }
        });

        botaoCadastrarPista.setText("Cadastrar");
        botaoCadastrarPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarPistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(221, 221, 221)
                            .addComponent(botaoCadastrarPista))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel28)
                                .addComponent(jLabel27)
                                .addComponent(jLabel29)
                                .addComponent(jLabel30))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(recordePista, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nomePista, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(paisPista, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(donoRecordePista, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(226, 226, 226))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(nomePista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(paisPista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(recordePista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(donoRecordePista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(botaoCadastrarPista)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pistas", jPanel6);

        jLabel31.setText("Tempo de qualificação:");

        jLabel32.setText("Quantidade de voltas:");

        jLabel33.setText("Pista:");

        botaoComecarQualificacao.setText("Começar");
        botaoComecarQualificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoComecarQualificacaoActionPerformed(evt);
            }
        });

        pistaCorrida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pistaCorridaMouseEntered(evt);
            }
        });
        jScrollPane9.setViewportView(pistaCorrida);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel33)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel32)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qtdVoltas, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel31)
                            .addGap(18, 18, 18)
                            .addComponent(qualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botaoComecarQualificacao))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdVoltas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(botaoComecarQualificacao)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Corridas", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEquipeActionPerformed

    private void apelidoEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apelidoEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apelidoEquipeActionPerformed

    private void nacionalidadeEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadeEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacionalidadeEquipeActionPerformed

    private void anoEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoEquipeActionPerformed

    private void pontosEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontosEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pontosEquipeActionPerformed

    private void botaoCadastrarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarEquipeActionPerformed
        if(nomeEquipe.getText().equals("") || apelidoEquipe.getText().equals("") || nacionalidadeEquipe.getText().equals("") || anoEquipe.getText().equals(""))
        JOptionPane.showMessageDialog(null,"Dados inválidos. Por favor, preencha os dados corretamente.");
        else {
            String aviso = Cliente.cadastrarEquipe(nomeEquipe.getText(), apelidoEquipe.getText(), nacionalidadeEquipe.getText(), anoEquipe.getText(), Double.parseDouble(pontosEquipe.getText()));
            JOptionPane.showMessageDialog(null, aviso);
        }
    }//GEN-LAST:event_botaoCadastrarEquipeActionPerformed

    private void nomePilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePilotoActionPerformed

    private void apelidoPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apelidoPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apelidoPilotoActionPerformed

    private void nascimentoPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nascimentoPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nascimentoPilotoActionPerformed

    private void nacionalidadePilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadePilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacionalidadePilotoActionPerformed

    private void pontosPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontosPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pontosPilotoActionPerformed

    private void botaoCadastrarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarPilotoActionPerformed
        /*if(emAtividade.isSelected() && (equipe.getText().equals("") || carro.getText().equals(""))) {
            JOptionPane.showMessageDialog(null,"Um piloto em atividade precisa ter um carro e uma equipe");
            return;
        } else if(!emAtividade.isSelected() && (equipe.getText() != "" || carro.getText() != "")) {
            JOptionPane.showMessageDialog(null,"Um piloto que não está em atividade não pode ter carro nem equipe");
            return;
        }

        if(Cliente.getListaCarros().get(Integer.parseInt(carro.getText())).getPiloto() != 0) {
            JOptionPane.showMessageDialog(null,"O carro informado já está sendo utilizado por outro piloto.");
            return;
        }

        if(nome.getText().equals("") || nascimento.getText().equals("") || nacionalidade.getText().equals(""))
        JOptionPane.showMessageDialog(null,"Dados inválidos. Por favor, preencha os dados corretamente.");
        else {*/
            Cliente.cadastrarPiloto(nomePiloto.getText(), apelidoPiloto.getText(), nascimentoPiloto.getText(), nacionalidadePiloto.getText(), listaCarrosPiloto.getSelectedIndex(), listaEquipesPiloto.getSelectedIndex(), emAtividade.isSelected(), Double.parseDouble(pontosPiloto.getText()));
            JOptionPane.showMessageDialog(null,"Piloto cadastrado com sucesso!");

            //mensagem.setText("Piloto cadastrado com sucesso");
            //}
    }//GEN-LAST:event_botaoCadastrarPilotoActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
    }//GEN-LAST:event_jPanel5MouseClicked

    private void nomePistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePistaActionPerformed

    private void paisPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisPistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paisPistaActionPerformed

    private void recordePistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordePistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recordePistaActionPerformed

    private void donoRecordePistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donoRecordePistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donoRecordePistaActionPerformed

    private void botaoCadastrarPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarPistaActionPerformed
        if(nomePista.getText().equals("") || paisPista.getText().equals("") || recordePista.getText().equals("") || donoRecordePista.getText().equals(""))
        JOptionPane.showMessageDialog(null,"Dados inválidos. Por favor, preencha os dados corretamente.");
        else {
            String aviso = Cliente.cadastrarPista(nomePista.getText(), paisPista.getText(), recordePista.getText(), donoRecordePista.getText());
            JOptionPane.showMessageDialog(null,aviso);
        }
    }//GEN-LAST:event_botaoCadastrarPistaActionPerformed

    private void botaoComecarQualificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoComecarQualificacaoActionPerformed
        try {
            /*if(nomeEquipe.getText().equals("") || apelidoEquipe.getText().equals("") || nacionalidadeEquipe.getText().equals("") || anoEquipe.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Dados inválidos. Por favor, preencha os dados corretamente.");
            else {
            int[] pil = Arrays.stream(pilotosCorrida.getText().split(",")).mapToInt(Integer::parseInt).toArray();
            Cliente.cadastrarCorrida(Integer.parseInt(qualificacao.getText()), Integer.parseInt(voltas.getText()), Integer.parseInt(pistaCorrida.getText()), pil);
            JOptionPane.showMessageDialog(null,"Corrida cadastrada com sucesso");
            }*/
            Cliente.enviarMensagem("Qualificação", qualificacao.getText());
            Cliente.qualificacao(pistaCorrida.getSelectedIndex());
        } catch (IOException ex) {
            Logger.getLogger(TelaFinal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(TelaFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoComecarQualificacaoActionPerformed

    private void BotaoAtualizarListaEquipesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAtualizarListaEquipesActionPerformed
        modelEquipes.clear();
        int qtd = Cliente.getListaEquipes().size();
        if(qtd > 0) {
            for(int i = 0; i < qtd; i++) {
                modelEquipes.addElement(Cliente.getListaEquipes().get(i).getId() + " - " + Cliente.getListaEquipes().get(i).getNome() + " - " + Cliente.getListaEquipes().get(i).getNacionalidade());
            }
            listaEquipes.setModel(modelEquipes);
        }
    }//GEN-LAST:event_BotaoAtualizarListaEquipesActionPerformed

    private void BotaoAtualizarListaPilotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAtualizarListaPilotosActionPerformed
        modelPilotos.clear();
        int qtd = Cliente.getListaPilotos().size();
        if(qtd > 0) {
            for(int i = 0; i < qtd; i++) {
                modelPilotos.addElement(Cliente.getListaPilotos().get(i).getId() + " - " + Cliente.getListaPilotos().get(i).getNome() + " - " + Cliente.getListaPilotos().get(i).getEquipe().getNome());
            }
            listaPilotos.setModel(modelPilotos);
        }
    }//GEN-LAST:event_BotaoAtualizarListaPilotosActionPerformed

    private void BotaoAtualizarListaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAtualizarListaCarroActionPerformed
        modelCarros.clear();
        //listaCarros.setLayout(absolute);
        int qtd = Cliente.getListaCarros().size();
        if(qtd > 0) {
            for(int i = 0; i < qtd; i++) {
                modelCarros.addElement(Cliente.getListaCarros().get(i).getId() + " - " + Cliente.getListaCarros().get(i).getNumero() + " - " + Cliente.getListaCarros().get(i).getMarca());
            }
            listaCarros.setModel(modelCarros);
        }
    }//GEN-LAST:event_BotaoAtualizarListaCarroActionPerformed

    private void BotaoAtualizarListaPistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAtualizarListaPistasActionPerformed
        modelPistas.clear();
        int qtd = Cliente.getListaPistas().size();
        if(qtd > 0) {
            for(int i = 0; i < qtd; i++) {
                modelPistas.addElement(Cliente.getListaPistas().get(i).getId() + " - " + Cliente.getListaPistas().get(i).getNome() + " - " + Cliente.getListaPistas().get(i).getPais());
            }
            listaPistas.setModel(modelPistas);
        }
    }//GEN-LAST:event_BotaoAtualizarListaPistasActionPerformed

    private void lerTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lerTagsActionPerformed
        try {
            Cliente.enviarMensagem("Ler tags", "Tags");
            Cliente.definirTags(Cliente.receberMensagem());
        } catch (IOException ex) {
            Logger.getLogger(TelaFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lerTagsActionPerformed

    private void botaoCadastrarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarCarroActionPerformed
        if(modeloCarro.getText().equals("") || marcaCarro.getText().equals("") || corCarro.getText().equals("") || numeroCarro.getText().equals(""))
        JOptionPane.showMessageDialog(null,"Dados inválidos. Por favor, preencha os dados corretamente.");
        else {
            String mensagem = Cliente.cadastrarCarro(listaTags.getSelectedValue(), modeloCarro.getText(), marcaCarro.getText(), corCarro.getText(), numeroCarro.getText(), listaEquipesCadastroCarro.getSelectedIndex());
            JOptionPane.showMessageDialog(null,mensagem);
        }
    }//GEN-LAST:event_botaoCadastrarCarroActionPerformed

    private void numeroCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroCarroActionPerformed

    private void corCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corCarroActionPerformed

    private void marcaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaCarroActionPerformed

    private void modeloCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloCarroActionPerformed

    private void botaoAtualizarTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarTagsActionPerformed
        modelTags.clear();
        int qtd = Cliente.getTags().length;
        if(qtd > 0) {
            for(int i = 0; i < qtd; i++) {
                modelTags.addElement(Cliente.getTags()[i]);
            }
            listaTags.setModel(modelTags);
        }
    }//GEN-LAST:event_botaoAtualizarTagsActionPerformed

    private void salvarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarDadosActionPerformed
        Cliente.escreverDados();
    }//GEN-LAST:event_salvarDadosActionPerformed

    private void listaEquipesCadastroCarroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaEquipesCadastroCarroMouseEntered
        modelEquipes.clear();
        int qtd = Cliente.getListaEquipes().size();
        if(qtd > 0) {
            for(int i = 0; i < qtd; i++) {
                modelEquipes.addElement(Cliente.getListaEquipes().get(i).getId() + " - " + Cliente.getListaEquipes().get(i).getNome() + " - " + Cliente.getListaEquipes().get(i).getNacionalidade());
            }
            listaEquipesCadastroCarro.setModel(modelEquipes);
        }
    }//GEN-LAST:event_listaEquipesCadastroCarroMouseEntered

    private void listaEquipesPilotoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaEquipesPilotoMouseEntered
        modelEquipes.clear();
        int qtd = Cliente.getListaEquipes().size();
        if(qtd > 0) {
            for(int i = 0; i < qtd; i++) {
                modelEquipes.addElement(Cliente.getListaEquipes().get(i).getId() + " - " + Cliente.getListaEquipes().get(i).getNome() + " - " + Cliente.getListaEquipes().get(i).getNacionalidade());
            }
            listaEquipesPiloto.setModel(modelEquipes);
        }
    }//GEN-LAST:event_listaEquipesPilotoMouseEntered

    private void listaCarrosPilotoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCarrosPilotoMouseEntered
        modelCarros.clear();
        int qtd = Cliente.getListaCarros().size();
        if(qtd > 0) {
            for(int i = 0; i < qtd; i++) {
                modelCarros.addElement(Cliente.getListaCarros().get(i).getId() + " - " + Cliente.getListaCarros().get(i).getNumero() + " - " + Cliente.getListaCarros().get(i).getMarca());
            }
            listaCarrosPiloto.setModel(modelCarros);
        }
    }//GEN-LAST:event_listaCarrosPilotoMouseEntered

    private void preencherDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preencherDadosActionPerformed
        JOptionPane.showMessageDialog(null, Cliente.preencherDados());
    }//GEN-LAST:event_preencherDadosActionPerformed

    private void pistaCorridaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pistaCorridaMouseEntered
        modelPistas.clear();
        int qtd = Cliente.getListaPistas().size();
        if(qtd > 0) {
            for(int i = 0; i < qtd; i++) {
                modelPistas.addElement(Cliente.getListaPistas().get(i).getId() + " - " + Cliente.getListaPistas().get(i).getNome() + " - " + Cliente.getListaPistas().get(i).getPais());
            }
            pistaCorrida.setModel(modelPistas);
        }
    }//GEN-LAST:event_pistaCorridaMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAtualizarListaCarro;
    private javax.swing.JButton BotaoAtualizarListaEquipes;
    private javax.swing.JButton BotaoAtualizarListaPilotos;
    private javax.swing.JButton BotaoAtualizarListaPistas;
    private javax.swing.JLabel LabelCarros;
    private javax.swing.JLabel LabelCarros1;
    private javax.swing.JLabel LabelCarros2;
    private javax.swing.JLabel LabelCarros3;
    private javax.swing.JTextField anoEquipe;
    private javax.swing.JTextField apelidoEquipe;
    private javax.swing.JTextField apelidoPiloto;
    private javax.swing.JButton botaoAtualizarTags;
    private javax.swing.JButton botaoCadastrarCarro;
    private javax.swing.JButton botaoCadastrarEquipe;
    private javax.swing.JButton botaoCadastrarPiloto;
    private javax.swing.JButton botaoCadastrarPista;
    private javax.swing.JButton botaoComecarQualificacao;
    private javax.swing.JTextField corCarro;
    private javax.swing.JTextField donoRecordePista;
    private javax.swing.JCheckBox emAtividade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton lerTags;
    private javax.swing.JList listaCarros;
    private javax.swing.JList<String> listaCarrosPiloto;
    private javax.swing.JList listaEquipes;
    private javax.swing.JList<String> listaEquipesCadastroCarro;
    private javax.swing.JList<String> listaEquipesPiloto;
    private javax.swing.JList listaPilotos;
    private javax.swing.JList listaPistas;
    private javax.swing.JList<String> listaTags;
    private javax.swing.JTextField marcaCarro;
    private javax.swing.JTextField modeloCarro;
    private javax.swing.JTextField nacionalidadeEquipe;
    private javax.swing.JTextField nacionalidadePiloto;
    private javax.swing.JTextField nascimentoPiloto;
    private javax.swing.JTextField nomeEquipe;
    private javax.swing.JTextField nomePiloto;
    private javax.swing.JTextField nomePista;
    private javax.swing.JTextField numeroCarro;
    private javax.swing.JTextField paisPista;
    private javax.swing.JList pistaCorrida;
    private javax.swing.JTextField pontosEquipe;
    private javax.swing.JTextField pontosPiloto;
    private javax.swing.JButton preencherDados;
    private javax.swing.JTextField qtdVoltas;
    private javax.swing.JTextField qualificacao;
    private javax.swing.JTextField recordePista;
    private javax.swing.JButton salvarDados;
    // End of variables declaration//GEN-END:variables
}
